version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: atlas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d atlas"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      target: server
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - server/.env.docker
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      target: client
      args:
        NEXT_PUBLIC_ASSISTANT_API: http://localhost:8000
    environment:
      NEXT_PUBLIC_ASSISTANT_API: http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres-data:
